---
- name: restart mtg
  service:
    name: mtg
    state: restarted

- name: systemd daemon-reload
  systemd:
    daemon_reload: yes
    
- name: cat /etc/mtg/config
  shell: cat /etc/mtg/config
  register: mtg_conf
  
- name: print mtg_conf
  debug:
    msg: "{{ mtg_conf.stdout_lines }}"