---
- name: ufw
  hosts: selfhost
  gather_facts: true
  become: true

  vars_prompt:
    - name: new_sshd_port
      prompt: "New sshd port"
      default: 22
      private: no

  roles:
    - role: ufw
      sshd_port: "{{ new_sshd_port }}"
