---
- name: V2ray
  hosts: selfhost
  gather_facts: true
  become: true

  vars:
    proxy_port: 8600
    proxy_from: "127.0.0.1:{{ proxy_port }}"

  vars_prompt:
    - name: email_addr
      prompt: "Email"
      default: "abc@gmail.com"
      private: no
    - name: domain_name
      prompt: "Domain name"
      default: "v.abc.com"
      private: no

  roles:
    - role: acme
    - role: nginx
      email: "{{ email_addr }}"
      domains:
        proxy:
          to: "{{ domain_name }}"
          from: "{{ proxy_from }}"
      srv_name: "v2ray"
    # - role: v2ray
    #   app_port: "{{ proxy_port }}"
